# Define pipeline stages
stages:
  - build
  - deploy

# Build job
build-backend:
  stage: build
  image: node:20
  script:
    - echo "Checking for Dockerfile..."
    - ls -la
    - echo "Installing backend dependencies..."
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 week
  only:
    - main
    - develop

# Deploy job
deploy-backend:
  stage: deploy
  image: docker:latest # Use Docker image
  services:
    - name: docker:dind # Docker-in-Docker service
      command: ["--insecure-registry=git.clp.kr:5050"]
  variables:
    DOCKER_DRIVER: overlay2
  script:
    # Install SSH client
    - echo "Installing OpenSSH client..."
    - apt-get update && apt-get install -y openssh-client
    - eval $(ssh-agent -s)

    # Set up SSH
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H ec2-44-203-85-14.compute-1.amazonaws.com >> ~/.ssh/known_hosts

    # Test SSH connection (optional, but helpful for debugging)
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@ec2-44-203-85-14.compute-1.amazonaws.com "echo 'SSH Connection Successful'"

    # Log into Docker registry
    - echo "Logging in to Docker registry..."
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

    # Build and push Docker image
    - echo "Building Docker image..."
    - docker build -t "$CI_REGISTRY_IMAGE/backend:latest" -f ./DockerFile .
    - echo "Pushing Docker image to the registry..."
    - docker push "$CI_REGISTRY_IMAGE/backend:latest"

    # Deploy the application on the EC2 instance
    - echo "Deploying backend using SSH..."
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@ec2-44-203-85-14.compute-1.amazonaws.com "
      cd /home/ubuntu/wavetrack-server &&
      git pull origin develop &&
      docker pull $CI_REGISTRY_IMAGE/backend:latest &&
      docker-compose -f /home/ubuntu/wavetrack-server/docker-compose.yml up -d --build
      "

  environment:
    name: production
    url: https://web.vottamean.com/api/v1
  only:
    - main
    - develop
 