# Define pipeline stages
stages:
  - build
  - deploy

# Build job
build-backend:
  stage: build
  image: node:20
  script:
    - echo "Checking for Dockerfile..."
    - ls -la
    - echo "Installing backend dependencies..."
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 week
  only:
    - main
    - develop

# Deploy job
deploy-backend:
  stage: deploy
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--insecure-registry=git.clp.kr:5050", "--debug"]
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_STARTUP_TIMEOUT: 120
  before_script:
    # Install OpenSSH client to avoid libcrypto errors
    - apt-get update && apt-get install -y openssh-client

    # Setup SSH keys for connecting to the EC2 instance
    - mkdir -p /home/gitlab-runner/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | base64 -d > /home/gitlab-runner/.ssh/id_rsa
    - chmod 600 /home/gitlab-runner/.ssh/id_rsa
    - ssh-keyscan -H ec2-44-203-85-14.compute-1.amazonaws.com >> /home/gitlab-runner/.ssh/known_hosts

    # Docker login for the private registry
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

  script:
    - echo "Building Docker image..."
    - docker build -t $CI_REGISTRY_IMAGE/backend:latest -f ./DockerFile .
    - echo "Pushing Docker image to the registry..."
    - docker push $CI_REGISTRY_IMAGE/backend:latest

    # SSH into EC2 instance and deploy with root privileges
    - echo "Deploying backend to EC2..."
    - ssh -vvv -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa ubuntu@ec2-44-203-85-14.compute-1.amazonaws.com "
      sudo -i bash <<EOF
      cd /home/ubuntu/wavetrack-server &&
      git pull origin develop &&
      docker pull $CI_REGISTRY_IMAGE/backend:latest &&
      sudo docker-compose -f /home/ubuntu/wavetrack-server/docker-compose.yml up -d --build
      EOF
      "

  environment:
    name: production
    url: https://web.vottamean.com/api/v1
  only:
    - main
    - develop
