# Define pipeline stages
stages:
  - build
  - deploy

# Cache node_modules to speed up subsequent builds
cache:
  paths:
    - node_modules/

# Build job
build-backend:
  stage: build
  image: node:20
  script:
    - echo "Installing backend dependencies..."
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 week
  only:
    - main
    - develop

# Deploy job
deploy-backend:
  stage: deploy
  image: docker:latest
  before_script:
    - echo "Preparing for deployment..."
    - apk update
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa  # Create the SSH key file
    - chmod 600 ~/.ssh/id_rsa                   # Set appropriate permissions
    - eval $(ssh-agent -s)                      # Start the SSH agent
    - ssh-add ~/.ssh/id_rsa                     # Add the SSH key to the agent
    - ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts  # Add EC2 host to known_hosts
  script:
    - echo "Deploying backend to EC2..."
    - ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST "
      cd /home/ubuntu/wavetrack-server &&
      git pull origin develop &&
      npm install &&
      sudo systemctl restart wavetrack-server.service"
  environment:
    name: production
    url: https://web.vottamean.com/api/v1
  only:
    - main
    - develop
  retry:
    max: 2
