# Define pipeline stages
stages:
  - build
  - deploy

# Cache node_modules to speed up subsequent builds
cache:
  paths:
    - node_modules/

# Build job
build-backend:
  stage: build
  image: node:20
  script:
    - echo "Installing backend dependencies..."
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 week
  only:
    - main
    - develop

# Deploy job
deploy-backend:
  stage: deploy
  before_script:
    - echo "Preparing for deployment..."
    - sudo apt-get update -y
    - sudo apt-get install -y openssh-client
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
  script:
    - echo "Deploying backend to EC2..."
    - ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST "
      cd /home/ubuntu/wavetrack-server &&
      git pull origin develop &&
      npm install &&
      sudo systemctl restart wavetrack-server.service"
  environment:
    name: production
    url: https://web.vottamean.com/api/v1
  only:
    - main
    - develop
  retry:
    max: 2
