# Define image
image: node:20

# Define pipeline stages
stages:
  - build
  - deploy

# Define variables
variables:
  PRODUCTION_DOMAIN: hexcode.anbschool.org/api/v1
  DEPLOY_USER: ubuntu
  DEPLOY_HOST: 13.212.6.189
  SSH_EC2_PRIVATE_KEY: $SSH_EC2_PRIVATE_KEY
  DIST_DEPLOY_PATH: /home/ubuntu/backend/

# Build job
build-backend:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - ./node_modules
  only:
    - develop
    - main

# Deploy job
deploy-backend:
  stage: deploy
  environment:
    name: production
    url: https://$PRODUCTION_DOMAIN
  before_script:
    - apt-get update -y && apt-get install -y openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_EC2_PRIVATE_KEY" | tr -d '\r' > private_key.pem
    - chmod 400 private_key.pem
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts

  script:
    - echo "Deploying to EC2 production with rsync..."
    # - rsync -avz -e "ssh -i private_key.pem" ./ ubuntu@$DEPLOY_HOST:$DIST_DEPLOY_PATH
    - rsync -avz --exclude='node_modules' --exclude='.git' -e "ssh -i private_key.pem" ./ ubuntu@$DEPLOY_HOST:$DIST_DEPLOY_PATH
    - ssh -i "private_key.pem" ubuntu@$DEPLOY_HOST "
        cd $DIST_DEPLOY_PATH
        npm install
        sudo systemctl restart backend.service &&
        sudo systemctl status backend.service
      "
  only:
    - develop
    - main
