version: '3'
services:
  backend:
    image: 'git.clp.kr:5050/anbschool/2nd/hexcode/team-projects/wavetrack-server/backend:latest'
    container_name: backend
    restart: always
    ports:
      - '8000:8000'
    environment:
      NODE_ENV: production
      DATABASE_URL: 'mysql://admin:hexcodeDB885@vottamean-db.cnag88eqc8ug.us-east-1.rds.amazonaws.com:3306/wavetrack'
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: 'npm start'
