# Specify the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Copy the docker-compose.yml file to the working directory
COPY docker-compose.yml /usr/src/app/docker-compose.yml

# Expose the port that your application will run on
EXPOSE 8000

# Define the command to start the application
CMD ["npm", "start"]
